.TH "MATE-POWER-MANAGER" "1" "29 March,2006" "" ""
.SH NAME
mate-power-manager \- MATE power manager userspace daemon
.SH SYNOPSIS
\fBmate-power-manager\fR [ \fB\-\-verbose\fR ] [ \fB\-\-debug\fR ] [ \fB\-\-help\fR ]
.SH "DESCRIPTION"
\fBmate-power-manager\fR is the backend program of the MATE power management infrastructure providing a complete and integrated solution to power management under the MATE desktop environment.
.PP
It supports features such as suspending, hibernating, screen blanking, cpu frequency switching and more in one small neat package.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-verbose\fR
Show extra debugging.
.TP
\fB\-\-no-daemon\fR
Do not detach \fBmate-power-manager\fR into the background so that error messages will be displayed on console.
.TP
\fB\-\-debug\fR
Only show specific debugging options. Useful for developers only.
.SH "SEE ALSO"
.PP
mate-power-preferences (1).
.SH "AUTHOR"
.PP
This manual page was written by Oliver Grawert <ogra@ubuntu.com> for
the Debian system and updated by Ow Mun Heng <nikeow@yahoo.com>
