.TH "MATE-POWER-PREFERENCES" "1" "11 July, 2005" "" ""
.SH NAME
mate-power-preferences \- MATE power preferences GUI
.SH SYNOPSIS
\fBmate-power-preferences\fR [ \fB\-\-verbose\fR ] [ \fB\-\-help\fR ]
.SH "DESCRIPTION"
\fBmate-power-preferences\fR is the gui program for the mate power management infrastructure
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-verbose\fR
Show extra debugging.
.SH "SEE ALSO"
.PP
mate-power-manager (1).
.SH "AUTHOR"
.PP
This manual page was written by Oliver Grawert <ogra@ubuntu.com> for
the Debian system.
