.TH "MATE-POWER-STATISTICS" "1" "11 December, 2007" "" ""
.SH NAME
mate-power-statistics \- MATE power statistics GUI
.SH SYNOPSIS
\fBmate-power-statistics\fR [ \fB\-\-verbose\fR ] [ \fB\-\-help\fR ]
.SH "DESCRIPTION"
\fBmate-power-statistics\fR is the gui program for the mate power management infrastructure.
.PP
It allows users to visualize the power consumption of laptop hardware.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-verbose\fR
Show extra debugging.
.SH "SEE ALSO"
.PP
mate-power-manager (1), mate-power-preferences (1).
.SH "AUTHOR"
.PP
This manual page was written by Simon Zheng <simon.zheng@sun.com>.
