.TH "MATE-POWER-BACKLIGHT-HELPER" "1" "21 April, 2014" "" ""
.SH NAME
mate-power-backlight-helper \- helper application for MATE's power management backlight control
.SH SYNOPSIS
\fBmate-power-backlight-helper\fR [ \fB\-\-help\fR ] [ \fB\-\-set-brightness\fR ] [ \fB\-\-get-brightness\fR ] [ \fB\-\-get-max-brightness\fR ]
.SH "DESCRIPTION"
\fBmate-power-backlight-helper\fR is a helper utility for controlling the backlight of TFT displays via the MATE power manager userspace daemon.
.PP
The \fBmate-power-backlight-helper\fR requires to be run with root privileges.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-set-brightness BRIGHTNESS_LEVEL\fR
Set the given brightness.
.TP
\fB\-\-get-brightness\fR
Get the current brightness.
.TP
\fB\-\-get-max-brightness\fR
Get the number of brightness levels supported.
.SH "SEE ALSO"
.PP
mate-power-manager (1).
.SH "AUTHOR"
.PP
This manual page has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for
the Debian system (but may be used by others).
