name: Release Version
on:
  push:
    tags:
      - "v*.*.*"

env:
  MATE_DESKTOP_VERSION: 1.28.2
  CACHE_PATH: /tmp/.cache

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install dependency packages
        run: sudo .github/workflows/ubuntu.sh

      - name: Install higher version Mate component packages
        run: sudo .github/workflows/mate-desktop.sh ${{env.MATE_DESKTOP_VERSION}} ${{ env.CACHE_PATH }}

      - name: Build the source code
        run: .github/workflows/builds.sh autotools

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        with:
          gh-cli-version: 2.72.0

      - name: Create github release
        run: |
          .github/workflows/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_SECRET: ${{ secrets.API_SECRET }}
